# Generated by Django 4.2.7 on 2024-03-19 15:43

import django.contrib.auth.models
from django.db import migrations, models
import javoblar.topshiriq__1.managers


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", javoblar.topshiriq__1.managers.SoftDeleteManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
