# Generated by Django 4.2.7 on 2024-03-19 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chat",
            name="initiator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_initiator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("receiver", "initiator"), ("initiator", "receiver")},
        ),
        migrations.RemoveField(
            model_name="chat",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="user2",
        ),
    ]
